### ISSUE TITLE
[socket] 유저 점수가 적용 안되는 버그

### ISSUE THREAD

**Issue by shseok** [06BOM/BOM-backend#11]
- 유저 점수가 스코어 판에 적용이 안됩니다. 수정부탁 드려요
  - pr이전 dev에서 발생했습니다. front console에서 userId 또한 userId:1로 같은 걸로 나타났습니다.
    - 두 유저의 userId는 달라야해용 (프론트 handleMakeRoom보면 1로 고정되있음 )
  - pr먼저 부탁드립니다

**Comment by gaheehee** [comment]
handleMakeRoom에 userId 고정한 이유는 아직 유저가 db에 1밖에 없어서 고정해놨습니다. 나중에 user 더 많아지면 거기다가 방 생성하는 userId 넣어서 emit 날려주시면 돼용~
