### ISSUE TITLE
[Plan] About Update Time

### ISSUE THREAD

**Issue by shseok** [06BOM/BOM-backend#9]
# 플랜 수정시 time도 가능할 수 있도록 해주면 감사하겠습니다.
- 프론트단에서 타이머 작동 후 해당 날짜의 플랜의 타임만 로컬에 저장되기 때문에 날짜 변경후 돌아오면 타임이 적용되지 않는 에러 발생. 따라서 해당 API가 필요합니다.

**Comment by LuBly** [comment]
dev에 해당 내용 업데이트 했어, local에서 확인은 해봤고 나중에 서버에 올리면 한번 더 확인 부탁해!!

**Comment by shseok** [comment]
응응 수고했어! 서버에 올리면 알려줘~
